### ISSUE TITLE
Support serialization of datetime.date

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-api#17]
This should be as simple as adding type check for `datetime.date` or `datetime.datetime` at https://github.com/pinax/pinax-api/blob/master/pinax/api/resource.py#L301 as the encode() should work for both types.

**Comment by grahamu** [comment]
@paltman the rfc3339.py functions only work with timestamps and require both date and time. This is by definition of RFC3339, see http://stackoverflow.com/questions/522251/whats-the-difference-between-iso-8601-and-rfc-3339-date-formats. We should not change these functions to additionally support date-only.

Nevertheless you make a good point, we could have utility functions to transcode dates. Text format should follow ISO8601 standard, i.e. "YYYY-MM-DD", and work with `datetime.date` objects. This would make a nice easy sprint task, thanks for the suggestion!

**Comment by brosner** [comment]
The change here is to add a type check for `datetime.date` in `resolve_value` and serialize it using `date.isoformat()`.

**Comment by jacobwegner** [comment]
Why not use [`DjangoJSONEncoder`](https://docs.djangoproject.com/en/1.9/topics/serialization/#djangojsonencoder)?

Would need to be passed to `json.dumps` using the `cls` kwarg:
https://docs.python.org/2/library/json.html#json.dumps

**Comment by brosner** [comment]
The way serialization is built in this app separates the serialization from the encoding. We need to have a serialized version before we get to `json.dumps`. This is needed to properly test without decoding and encoding again. If there is a way to get the encoding without the serialization then I am game for using something within Django.

**Comment by grahamu** [comment]
Resolved by https://github.com/pinax/pinax-api/pull/21.
