### ISSUE TITLE
help with installing pinax-api 

### ISSUE THREAD

**Issue by philiptolk** [pinax/pinax-api#27]
pip install -vvv pinax-api
Collecting pinax-api
  1 location(s) to search for versions of pinax-api:
  * https://pypi.python.org/simple/pinax-api/
  Getting page https://pypi.python.org/simple/pinax-api/
  Looking up "https://pypi.python.org/simple/pinax-api/" in the cache
  Current age based on date: 577
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 577
  Analyzing links from page https://pypi.python.org/simple/pinax-api/
  Could not find a version that satisfies the requirement pinax-api (from versions: )
Cleaning up...
No matching distribution found for pinax-api

**Comment by KatherineMichel** [comment]
Sorry to be late to this. There do not appear to be any files on PyPi for this app. I'm sure why there is an app page there without files to install. The app hasn't been updated in some time, but in the interest of closing out your issue, you can install this app directly from this repo if you are still interested. Let me know if you need more assistance.
